version: '3'

services:
  bundle:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - bundler_gems:/usr/local/bundle
    entrypoint: bundle
    command: exec rake build:serve
    ports:
      - 4000:4000

  npm:
    image: mcr.microsoft.com/playwright:v1.41.1-jammy
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    ipc: host
    entrypoint: npm

volumes:
  bundler_gems:
